baseURL = "https://waltermas-gitter.github.io/hugopapers/"
languageCode = "en-us"
title = "Hugo papers"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
DefaultContentLanguage = "en"
disableLanguages = ["en-us"]
defaultContentLanguageInSubdir = false

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[params]
  enableSearch = true
  userStatusEmoji = "😀"
  author = "waltermas"
  description = "waltermas hugo papers"
  github = "waltermas-gitter"
  avatar = "images/avatar.jpg"
  favicon = "images/favicon.png"
  headerIcon = "images/favicon.png"
