baseURL = "https://waltermas-gitter.github.io/hugopapers/"
languageCode = "en-us"
title = "Hugo papers"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[outputs]
  home = ["HTML", "JSON"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[params]
  enableSearch = true
  userStatusEmoji = "😀"
  author = "waltermas"
  description = "waltermas hugo papers"
  github = "waltermas-gitter"
  avatar = "/images/avatar.jpg"
  favicon = "/images/favicon.png"
  headerIcon = "/images/favicon.png"
